/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.gui;

import Clientes.Titular;
import Extra.Segooros;
import java.awt.LayoutManager;
import Exceptions.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogo
 */
public class FormSaude extends javax.swing.JPanel {

    private Segooros emp;
    /**
     * Creates new form FormSaude
     */
    public FormSaude() {
        initComponents();
    }

    public FormSaude(Segooros emp) {
        this();
        this.emp=emp;
    }
    
    public void SetSegooros(Segooros emp)
    {
        this.emp=emp;
    }
    
    private void Limpar()
    {
        jTextField4.setText("");
        jTextField5.setText("");
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID Titular:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Preco Inicial:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Seguro de Saude");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean existeT=false;
        try
        {
            for(Titular T : emp)
            {
                if(T.getIDtitular()==Integer.parseInt(jTextField4.getText()))
                {
                    existeT=true;
                    try
                    {
                        if(T.getIdade()<17)
                        {

                            if(Double.parseDouble(jTextField5.getText())==100)
                            {
                                T.criarSeguroSaude(Double.parseDouble(jTextField5.getText()));
                                JOptionPane.showMessageDialog(null, "O seu seguro foi criado com sucesso.");

                            }
                            else
                                throw new ValorBaseJuniorNaoAtingidoException("O valor do Seguro de "
                                        + "Saude Junior tem um Preço fixo de 100");
                        }
                        else if(T.getIdade()>=17 && T.getIdade()<=80)
                        {
                            if(Double.parseDouble(jTextField5.getText())>=150)
                            {
                                T.criarSeguroSaude(Double.parseDouble(jTextField5.getText()));
                                JOptionPane.showMessageDialog(null, "O seu seguro foi criado com sucesso.");

                            }
                            else
                                throw new ValorBaseAdulto_SeniorNaoAtingidoException("O Valor Base do "
                                        + "Seguro de Saude Adulto e Senior e de 150");
                        }
                        else if(T.getIdade()>80)
                        {
                            throw new IdadeDoTitularNaoPodeTerSeguroSaudeException("O titular "
                                    + "Introduzido nao pode criar um seguro de saude pois "
                                    + "ja tem mais de 80 anos.");
                        }
                    }
                    catch(NumberFormatException e)
                    {
                        JOptionPane.showMessageDialog(null, "O valor do Preco introduzido nao e valido.");
                    }
                    
                }
            }
            if(existeT==false)
                throw new TitularNaoExisteException("O ID do titular nao existe.");
        }
        catch(TitularNaoExisteException |ValorBaseJuniorNaoAtingidoException | ValorBaseAdulto_SeniorNaoAtingidoException | IdadeDoTitularNaoPodeTerSeguroSaudeException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Limpar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
